services:
  # Backend Service
  - type: web
    name: cropai-backend
    runtime: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: USE_OPENAI
        value: "0"
    healthCheckPath: /

  # Frontend Service
  - type: web
    name: cropai-frontend
    runtime: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: VITE_API_URL
        fromService:
          name: cropai-backend
          type: web
          property: host
